version: "3.8"
services:
  label_studio:
    image: heartexlabs/label-studio:latest
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
    volumes:
      - ./data:/label-studio/data
    ports:
      - "8080:8080"
