version: "3.8"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: >
      mlflow server --backend-store-uri sqlite:///mlflow.db
                    --default-artifact-root /mlflow/storage
                    --host 0.0.0.0
    volumes:
      - ./storage:/mlflow/storage
    ports:
      - "5000:5000"
