# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Python & YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install linters
        run: |
          pip install flake8 yamllint

      - name: Lint Python code
        run: flake8 .

      - name: Lint YAML files
        run: yamllint -c .yamllint.yml .

  build:
    name: Build Docker Compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build all services
        run: docker-compose -f docker-compose.yml build --pull

      - name: Validate Compose file
        run: docker-compose -f docker-compose.yml config
